Revert to 1.10 series.
Reverted to 1.10.4 (1.10.4 series). While under 1.11 most Go-based software will successfully compile (including my own which uses runtime directly), any software which relies on the Mage build system, such as Hugo, will fail. This is largely seen by the below mentioned error. While this may be fixed in master, just the changes to runtime and internal/cpu alone (that largely do away with CacheLineSize) are too substantial to backport to 1.11, and therefore I'm opting to rollback to 1.10. Without the ability to build Hugo, I'm unable to address issues or perform reversions with it, and thus this negatively impacts my ability to communicate development to our community via the Solus website (which leverages Hugo).

```
Error: failed to check types in directory: magefile.go:6:2: could not import bytes (type-checking package "bytes" failed (/usr/lib64/golang/src/bytes/buffer.go:11:2: could not import io (type-checking package "io" failed (/usr/lib64/golang/src/io/pipe.go:12:2: could not import sync (type-checking package "sync" failed (/usr/lib64/golang/src/sync/pool.go:9:2: could not import runtime (type-checking package "runtime" failed (/usr/lib64/golang/src/runtime/alg.go:8:2: could not import internal/cpu (type-checking package "internal/cpu" failed (/usr/lib64/golang/src/internal/cpu/cpu_x86.go:9:7: CacheLineSize redeclared in this block))))))))))
```

Additionally, this update applies an updated patch which strips away tests which are known to be problematic in the 1.10 series against the latest binutils.